api/urls.py
from django.urls import path
from .views import add_reaction, delete_reaction, list_reactions

urlpatterns = [
    path('reactions/', list_reactions),
    path('reactions/add/', add_reaction, name='add-reaction'),
    path('reactions/delete/<int:reaction_id>/', delete_reaction),
]

blog/urls.py
from django.urls import path
from .views import PostListView,PostUpdateView, PostDeleteView,PostCreateView,AddLikesPost,AddLikesComment,AddLikesReply,AddCategoryView    
from . import views
from .views import load_more_posts

urlpatterns = [
    # path('categories/<slug:category_slug>/', views.category, name='category'),
    path('add-category/', AddCategoryView.as_view(), name='add-category'),
    path('category/<str:cats>/', views.CategoryView, name='view-category'),
    path('tags/<slug:tag_slug>/', views.tags, name='tags') , # Example URL pattern
    path('', PostListView.as_view(), name='post-list'),
    path('search/', views.search_view, name='post-search'),
    path('load_more_posts/', load_more_posts, name='load-more-posts'),
    path('post-detail/<uuid:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('newpost', PostCreateView.as_view(), name='post-create'),
    path('update/<uuid:pk>/', PostUpdateView.as_view(), name='post-update'),
    # path('like/<uuid:pk>/', AddLike, name='post-likes'),
    path('add-like/<uuid:pk>/', AddLikesPost, name='add-post-likes'),
    path('add-like-comment/<uuid:pk>/', AddLikesComment.as_view(), name='add-comment-likes'),
    path('add-like-reply/<uuid:pk>/', AddLikesReply.as_view(), name='add-reply-likes'),
    # path('comment-like/<uuid:pk>/', AddCommentLike, name='comment-likes'),
    # path('post/<uuid:pk>/comment/create/', CommentCreateView.as_view(), name='comment-create'),
    # path('reply-like/<uuid:pk>/', AddReplyLike, name='reply-likes'),
    # path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment-update'),
    path('<uuid:pk>/delete/', PostDeleteView.as_view(), name='post-delete')
]

blogport/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('post/', include('blog.urls')),
    # path('api/', include('api.urls')),
    path('auth0/', include('authentication.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete
from django.utils.text import slugify
from django.urls import reverse
import uuid
# from comment.models import GenericRelation,Reaction


# from notification.models import Notification

# Create your models here.

# uploading user files to a specific directory
def user_directory_path(instance, filename):
    return 'user_{0}/{1}'.format(instance.author.id, filename)




class Tag(models.Model):
    title = models.CharField(max_length=255, verbose_name="Tag")
    image = models.ImageField(upload_to=user_directory_path, verbose_name="Tag Images")
    slug = models.SlugField(null=False, unique=True, default=uuid.uuid1) 
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def save(self, *args, **kwargs):
        # Set the author to the admin user
        admin_user = User.objects.get(username='Netphixs')  # Replace 'admin' with the username of your admin user
        self.author = admin_user
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    def get_absolute_url(self):
        return reverse("tags", args=[self.slug])

    def __str__(self) -> str:
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

class Categorys(models.Model):
    name = models.CharField(max_length=255, verbose_name="Category")

    def get_absolute_url(self):
        return reverse("post-list")

    def __str__(self) -> str:
        return self.name

    


# from django.db import models
# from django.contrib.auth.models import User

# class PostFileContent(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='content_owner')
#     file = models.FileField(upload_to=user_directory_path)
    
#     def __str__(self):
#         return self.file.name

#     def save(self, *args, **kwargs):
#         # Extract the request object from kwargs
#         request = kwargs.pop('request', None)
        
#         # If the user is not set and a request object is available, set the user to the current user
#         if not self.user_id and request:
#             self.user = request.user
        
#         super(PostFileContent, self).save(*args, **kwargs)



class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    title = models.CharField(max_length=255, verbose_name="Title")
    content = models.TextField(verbose_name="Content")
    picture = models.ImageField(upload_to=user_directory_path, verbose_name="Picture")
    tag = models.ManyToManyField(Tag, related_name="posts", verbose_name="Tags")
    category = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    posted = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, verbose_name='posts_likes', related_name='posts_likes')
    
    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.title + ' | ' + str(self.author)
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_absolute_url(self):
        return reverse("post-detail", args=[str(self.id)])
    
class Visit(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.post.title # Customize as per your requirement


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="post_likes")

    def user_liked_post(sender, instance, *args, **kwargs):
        like = instance
        post = like.post
        sender = like.user
        # notify = Notification(post=post, sender=sender, user=post.user)
        # notify.save()

    def user_unliked_post(sender, instance, *args, **kwargs):
        like = instance
        post = like.post
        sender = like.user
        # notify = Notification.objects.filter(post=post, sender=sender, notification_types=1)
        # notify.delete()

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404,reverse
# from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, CreateView, UpdateView, DeleteView,DetailView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post,Tag,Categorys
from django.views.generic import View
from comment.forms import CommentForm
from comment.models import Comment, Reply,Reaction,AnonymousLike
from .forms import NewPostForm
from django.http import HttpResponseRedirect
from django.template.loader import render_to_string
from django.views.generic import FormView
from django.http import JsonResponse
from .forms import SearchForm
from .models import Visit
from django.http import HttpResponseNotFound
from django.http import HttpResponseBadRequest




class PostListView(ListView):
    model = Post
    template_name = 'blog.html'  # Specify the template name
    # context_object_name = 'posts'  # Specify the context variable name in the template
    ordering = "-posted"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('-posted')[:4]  # Pass all tags to the template
        context['tags'] = Tag.objects.all()  # Pass all tags to the template
        context['category'] = Categorys.objects.all()  # Pass all categories to the template
        return context
    
def tags(request, tag_slug):
    tag = get_object_or_404(Tag, slug=tag_slug)
    posts = Post.objects.filter(tag=tag).order_by("-posted")  # Assuming you have a 'tags' field in your Post model
    tags = Tag.objects.all()  # Fetch all tags
    first_post = posts.first()  # Fetch the first post for the tag
    first_post_picture = first_post.picture.url if first_post else None  # Get the picture URL of the first post, or None if no post exists
    category = Categorys.objects.all()
    category = Categorys.objects.all()  # Fetch all categories
    context = {
        'tag': tag,
        'posts': posts,
        'tags': tags,
        'first_post': first_post,
        'first_post_picture': first_post_picture,
        'category': category,  # Pass categories to the context
    }
    return render(request, "tag.html", context)

class AddCategoryView(CreateView):
    model = Categorys
    template_name = 'add_category.html'
    fields = '__all__'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all().order_by('-posted') # Pass all tags to the template
        context['tags'] = Tag.objects.all()  # Pass all tags to the template
        context['category'] = Categorys.objects.all()  # Pass all categories to the template
        return context
    
import json
    
# def AddLike(request, pk):

#     post = get_object_or_404(Post, id=request.POST.get('post_id'))
#     liked = False
#     if post.likes.filter(id=request.user.id).exists():
#         post.likes.remove(request.user)
#         liked = False
#     else:
#         post.likes.add(request.user)
#         liked = True
#     return HttpResponseRedirect(reverse('post-detail', args=[str(pk)]))
    
def AddLikesPost(request, pk):
    data = json.loads(request.body)
    id = data["id"]
    post = Post.objects.get(id=id)
    checker = None
    
    if request.user.is_authenticated:
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
            checker = 0
        else:
            post.likes.add(request.user) 
            checker = 1
            
    likes = post.likes.count()
    
    # Determine the liked status based on the current user's interaction
    liked = post.likes.filter(id=request.user.id).exists() if request.user.is_authenticated else False
    
    info = {
        'check': checker,
        'num_of_likes': likes,
        'liked': liked,  # Include the liked status in the JSON response
    }
    
    return JsonResponse(info)

class AddLikesComment(View):
    def post(self, request, *args, **kwargs):
        comment_id = request.POST.get('comment_id')
        comment = get_object_or_404(Comment, id=comment_id)
        liked = False

        if request.user.is_authenticated:
            if comment.likes.filter(id=request.user.id).exists():
                comment.likes.remove(request.user)
                liked = False
            else:
                comment.likes.add(request.user)
                liked = True

        # Include the comment ID in the JSON response
        data = {
            'comment_id': comment_id,
            'liked': liked,
            'numb_of_likes': comment.likes.count(),
        }

        return JsonResponse(data)
    
class AddLikesReply(View):
    def post(self, request, *args, **kwargs):
        reply_id = request.POST.get('reply_id')
        reply = get_object_or_404(Reply, id=reply_id)
        liked_reply = False

        if request.user.is_authenticated:
            if reply.likes.filter(id=request.user.id).exists():
                reply.likes.remove(request.user)
                liked_reply = False
            else:
                reply.likes.add(request.user)
                liked_reply = True

        # Include the comment ID in the JSON response
        data = {
            'reply_id': reply_id,
            'liked_reply': liked_reply,
            'numb_of_likes': reply.likes.count(),
        }

        return JsonResponse(data)






# def AddReplyLike(request, pk):
#     # Get the reply object
#     reply = get_object_or_404(Reply, id=request.POST.get('reply_id'))
#     if request.user.is_authenticated:
#         # Check if the user has already liked the reply
#         if reply.likes.filter(id=request.user.id).exists():
#             # User has already liked the reply, so unlike it
#             reply.likes.remove(request.user)
#             liked_reply = False
#         else:
#             # User hasn't liked the reply, so like it
#             reply.likes.add(request.user)
#             liked_reply = True
#     else:
#         # User is not authenticated, use IP address to track likes
#         ip_address = request.META.get('REMOTE_ADDR')
#         if AnonymousLike.objects.filter(reply=reply, ip_address=ip_address).exists():
#             # If the like already exists, remove it
#             AnonymousLike.objects.filter(reply=reply, ip_address=ip_address).delete()
#             liked_reply = False
#         else:
#             # If the like does not exist, create it
#             AnonymousLike.objects.create(reply=reply, ip_address=ip_address)
#             liked_reply = True

#     # Redirect back to the post detail page
#     return HttpResponseRedirect(reverse('post-detail', args=[str(pk)]))

def CategoryView(request, cats):
    category = get_object_or_404(Categorys, name=cats)
    category_posts = Post.objects.filter(category=category)  # Assuming you have a related_name in the ManyToManyField
    
    tags = Tag.objects.all()
    categories = Categorys.objects.all()
    posts = Post.objects.all()
    
    context = {
        'category': category,
        'category_posts': category_posts,
        'tags': tags,
        'posts': posts,
        'categories': categories,
    }
    return render(request, 'category.html', context)




class PostDetailView(DetailView):
    model = Post
    template_name = "post-details.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()  # Pass all tags to the template
        context['category'] = Categorys.objects.all()  # Pass all categories to the template
          # Pass all categories to the template
        post = self.get_object()
        # categories = Category.objects.all()
        context['categories'] = Categorys.objects.all()
        comments = Comment.objects.filter(post=post).order_by('-date')
        context['comments'] = comments  # Pass comments to the template
        post = get_object_or_404(Post, id=self.kwargs['pk'])
        total_likes = post.total_likes()
        
        liked = False
        if self.request.user.is_authenticated:  # Check if user is authenticated
            if post.likes.filter(id=self.request.user.id).exists():
                liked = True
        context['total_likes'] = total_likes
        context['liked'] = liked  # Pass liked status to the template
        
        # Retrieve comment_id from POST data
        comment_id = self.request.POST.get('comment_id')
        if comment_id:
            comment = get_object_or_404(Comment, id=comment_id)
            totals_likes = comment.total_likes()
            liked_comment = False
            if comment.likes.filter(id=self.request.user.id).exists():
                liked_comment = True
            context['totals_likes'] = totals_likes
            context['liked_comment'] = liked_comment  # Pass liked_comment status to the template
            
        reply_id = self.request.POST.get('reply_id')
        if reply_id:
            liked_reply = False
            reply = get_object_or_404(Reply, id=reply_id)
            total_reply_likes = reply.total_reply_likes()
            liked_reply = False
            if reply.likes.filter(id=self.request.user.id).exists():
                liked_reply = True
            context['total_reply_likes'] = total_reply_likes
            context['liked_reply'] = liked_reply
        # Retrieve reaction data for each comment
        reaction_data = {}
        for comment in comments:
            reactions = Reaction.objects.filter(comment=comment)
            reaction_data[comment.id] = {reaction.reaction_type: reaction.user.username for reaction in reactions}
        context['reaction_data'] = reaction_data  # Pass reaction data to the template

templates/footer.html
{% load static %}
<footer class="container" id="footer">
    <section class="footersec flex">
      <div class="logofooter">
        <div class="logof">
          <a href="/" class="flex">
            <img src="{% static '' %}assests/images/img/logo.png" alt="" />
            <h1>Netphixs</h1>
          </a>
        </div>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci,
          reprehenderit esse? Architecto, adipisci reiciendis! Esse quam
          reiciendis ex mollitia veniam.
        </p>
        <h4>Address</h4>
        <p>123 lorem street</p>
        <p>Awka, Nigeria</p>
      </div>
      <div class="categoriesfooter">
        <h3>Categories/Tags</h3>
        <div class="flex">
          <div class="catefbx">
            <ul>
              {% for category in categories|slice:":5" %}
              <li><a href="{% url "view-category" category.name %}">{{category.name|title}}</a></li>
              {% endfor %}
            </ul>
          </div>
          <div class="catefbx">
            <div></div>
            <ul class="catefbxa">
              {% for tag in tags|slice:":5" %} 
              <li><a href="{% url "tags" tag.slug %}">#{{tag.title}}</a></li>
              {% endfor %}
          </div>
        </div>
      </div>
      <div class="newsletterfooter">
        <h3>Newsletter</h3>
        <p>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit.
          Voluptates, ipsa.
        </p>
        <div class="alert alert-dismissible flex" id="newsletter-message" style="display: none;" role="alert">
          <span id="messageContent"></span>
          <span class="clear-btnn" id="clearBtnn">&times;</span>
      </div>
        <form action="{% url "newsletter" %}" method="POST" id="newsletter-form" class="flex"> 
          {% csrf_token %}
          <div class="flex">
              <i class="fa-regular fa-user"></i>
              <input type="name" name="name" placeholder="Your Name" id="name" />
          </div>
          <div class="flex">
              <i class="fa-regular fa-envelope"></i>
              <input type="email" name="email" placeholder="Email Address" id="email" /> 
          </div>
          <button type="submit">
              Subscribe<i class="fa-solid fa-arrow-right"></i>
          </button>
      </form>
      </div>
    </section>
    <div class="themeauthor container flex">
      <div class="createdby">
        <h4>
          &copy; 2024 Created by
          <a href="/" target="_blank" title="">Netphixs</a>. All rights
          reserved.
        </h4>
      </div>
      <div class="social flex">
        <div class="social-icon">
          <a href="#" class="flex">
            <i class="fa-brands fa-twitter"></i>
            <h4>Twitter</h4>
          </a>
        </div>
        <div class="social-icon">
          <a href="#" class="flex">
            <i class="fa-brands fa-square-facebook"></i>
            <h4>Facebook</h4>
          </a>
        </div>
        <div class="social-icon">
          <a href="#" class="flex">
            <i class="fa-brands fa-instagram"></i>
            <h4>Instagram</h4>
          </a>
        </div>
        <div class="social-icon">
          <a href="#" class="flex">
            <i class="fa-brands fa-linkedin"></i>
            <h4>Linkedin</h4>
          </a>
        </div>
      </div>
    </div>
  </footer>
    <a class="back-to-top active" data-back-to-top aria-label="back-to-top" href="#top"><i class="fa fa-arrow-up" aria-hidden="true"></i></a>
    

templates/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block header %} {% include "header.html" %} {% endblock header %}
{% block content %}
<!-- =====About Section Ends===== -->
<section class="about section " id="about">
    <div class="container">
      <div class="row bg-color">
        <div class="section-title padd-15" style="margin-bottom: -20px;">
          <h2>LOGIN</h2>
        </div>
      </div>
      <div class="row row-signup">
        <div class="wrapper">
          <form action="{% url "login" %}" method="POST">
            {% csrf_token %}
            <div class="input-box">
              <input type="text" placeholder="Username" name="username" required>
              <i class="fa fa-user" aria-hidden="true"></i>
            </div>
            <div class="input-box input-pass" style="margin-bottom: 25px;">
              <input type="password" placeholder="Password" required name="password" id="password1">
              <i class="fa-solid fa-lock" id="passwordIcon1"></i>
            </div>
            <div class="remember-forgot">
              <label for="check">
                <input type="checkbox" name="remember">
                Remember Me
              </label>
              <a href="/">Forgotten Password</a>
            </div> 
            <button type="submit" class="btn">Login</button>
            <div class="register-link">
              <p>Already have an account? <a href="{% url "sign-up" %}">signup</a></p>
            </div>
          </form>
        </div>
        </div>
      </div>
  </section>
  <!-- =====About Section Ends===== -->
{% endblock content %}
{% block footer %}{% include "footer.html" %}{% endblock footer %}

templates/newpost.html
{% extends "base.html" %}
{% load static %}
{% block scripts %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function() {
      $('#id_picture').attr('placeholder', 'Enter picture');
      $('#id_title').attr('placeholder', 'Enter title');
      $('#id_content').attr('placeholder', 'Enter content');
      $('#id_tag').attr('placeholder', 'Enter tag');
      $('#id_category').attr('placeholder', 'Enter category');
    });
  </script>
{% endblock scripts %}
{% block title %}Add Post{% endblock title %}
{% block header %} {% include "header.html" %} {% endblock header %}
{% block content %}
  <!-- =====About Section Ends===== -->
  <section class="about section " >
    <div class="container">
      <div class="row bg-color">
        <div class="section-title padd-15" style="margin-bottom: -60px;">
          <h2>Upload Post</h2>
        </div>
      </div>
      <div class="row row-signup">
        <div class="content-section">
            <form action="{% url "post-create" %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom textcolor">POST</legend>
                    {% comment %} <div class="form-group">
                        <label for="files">Upload Post</label>
                        <input type="file" name="files" id="files" placeholder="Upload a post">
                    </div>
                    <div class="form-group">
                        <label for="video_url">Video Url</label>
                        <input type="text" id="video_url" name="video_url" placeholder="video url">
                    </div>
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" name="title" id="title" placeholder="post title">
                    </div>
                    <div class="form-group">
                        <label for="category">Category</label>
                        <select name="category" id="category" class="input" multiple>
                            {% for category in categories %}
                            <option value="{{ category.id }}">{{ category.name }}</option>
                            {% endfor %}
                            <option value="other">Other</option>
                        </select>
                        <input type="text" id="new_category" name="new_category" placeholder="Enter new category" style="display: none;">
                    </div>
                    <div class="form-group">
                        <label for="tags">Tags</label>
                        <select name="tags" id="tags" class="input" multiple>
                            {% for tag in tags %}
                            <option value="{{ tag.id }}">{{ tag.name }}</option>
                            {% endfor %}
                            <option value="other">Other</option>
                        </select>
                        <input type="text" id="new_tag" name="new_tag" placeholder="Enter new tag" style="display: none;">
                    </div>
                    <div class="form-group">
                        <label for="content">Content</label>
                        <textarea name="content" id="content" placeholder="description"></textarea>
                    </div> {% endcomment %}
                    {% comment %} {{form.picture}} <br><br>
                    {{form.title}} <br><br>
                    {{form.content}} <br><br>
                    {{form.tag}} <br><br>
                    {{form.category}} <br><br> {% endcomment %}
                    <div>
                        <label for="id_picture">Picture:</label>
                        {{ form.picture }}
                      </div><br>
                      <div>
                        <label for="id_title">Title:</label>
                        {{ form.title }}
                      </div><br>
                      <div>
                        <label for="id_content">Content:</label>
                        {{ form.content }}
                      </div><br>
                      <div>
                        <label for="id_tag">Tags:</label>
                        {{ form.tag }}
                      </div><br>
                      <div>
                        <label for="id_category">Category:</label>
                        {{ form.category }}
                      </div><br>
                    <button type="submit" class="btn btn-primary">Add Post</button>
                </fieldset>
            </form>
            
        </div>
        </div>
      </div>
  </section>
  <!-- =====About Section Ends===== -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function() {
      $('#id_title').attr('placeholder', 'Enter title');
      $('#id_content').attr('placeholder', 'Enter Content');
      $('#id_category').attr('placeholder', 'Enter Category');
    });
  </script>
{% endblock content %}
{% block footer %}{% include "footer.html" %}{% endblock footer %}

templates/update_post.html
{% extends "base.html" %}
{% load static %}
{% block title %}Update-Post{% endblock title %}
{% block header %} {% include "header.html" %} {% endblock header %}
{% block content %}
  <!-- =====About Section Ends===== -->
  <section class="about section " >
    <div class="container">
      <div class="row bg-color">
        <div class="section-title padd-15" style="margin-bottom: -60px;">
          <h2>Update Post</h2>
        </div>
      </div>
      <div class="row row-signup">
        <div class="content-section">
            <form action="{% url "post-update" post.pk %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom textcolor">POST</legend>
                    {% comment %} <div class="form-group">
                        <label for="files">Upload Post</label>
                        <input type="file" name="files" id="files" placeholder="Upload a post">
                    </div>
                    <div class="form-group">
                        <label for="video_url">Video Url</label>
                        <input type="text" id="video_url" name="video_url" placeholder="video url">
                    </div>
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" name="title" id="title" placeholder="post title">
                    </div>
                    <div class="form-group">
                        <label for="category">Category</label>
                        <select name="category" id="category" class="input" multiple>
                            {% for category in categories %}
                            <option value="{{ category.id }}">{{ category.name }}</option>
                            {% endfor %}
                            <option value="other">Other</option>
                        </select>
                        <input type="text" id="new_category" name="new_category" placeholder="Enter new category" style="display: none;">
                    </div>
                    <div class="form-group">
                        <label for="tags">Tags</label>
                        <select name="tags" id="tags" class="input" multiple>
                            {% for tag in tags %}
                            <option value="{{ tag.id }}">{{ tag.name }}</option>
                            {% endfor %}
                            <option value="other">Other</option>
                        </select>
                        <input type="text" id="new_tag" name="new_tag" placeholder="Enter new tag" style="display: none;">
                    </div>
                    <div class="form-group">
                        <label for="content">Content</label>
                        <textarea name="content" id="content" placeholder="description"></textarea>
                    </div> {% endcomment %}
                    {% comment %} {{form.picture}} <br><br>
                    {{form.title}} <br><br>
                    {{form.content}} <br><br>
                    {{form.tags}} <br><br>
                    {{form.category}} <br><br> {% endcomment %}
                    <div>
                        <label for="id_picture">Picture:</label>
                        {{ form.picture }}
                      </div><br>
                      <div>
                        <label for="id_title">Title:</label>
                        {{ form.title }}
                      </div><br>
                      <div>
                        <label for="id_content">Content:</label>
                        {{ form.content }}
                      </div><br>
                      <div>
                        <label for="id_tag">Tags:</label>
                        {{ form.tag }}
                      </div><br>
                      <div>
                        <label for="id_category">Category:</label>
                        {{ form.category }}
                      </div><br>
                    <button type="submit" class="btn btn-primary">Update Post</button>
                </fieldset>
            </form>
            
        </div>
        </div>
      </div>
  </section>
  <!-- =====About Section Ends===== -->
{% endblock content %}
{% block footer %}{% include "footer.html" %}{% endblock footer %}